# Generated by Django 3.1.7 on 2021-03-24 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20210324_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='admin',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Faol'), (0, 'Nofaol')], default=1),
        ),
    ]
